name: Linux
on:
  push:
    branches: ['*']
    tags-ignore: ['*']
  pull_request:

jobs:
  raku:
    strategy:
      matrix:
        raku-version: ['2025.08', 'latest']
        duckdb-version: ['1.1.1']
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install -y curl wget unzip
      - name: Install DuckDB library
        run: |
          wget https://github.com/duckdb/duckdb/releases/download/v${{ matrix.duckdb-version }}/libduckdb-linux-amd64.zip
          unzip libduckdb-linux-amd64.zip
          sudo cp libduckdb.so /usr/lib
      - name: Install DuckDB binary
        run: |
          curl https://install.duckdb.org | sh
          echo "$HOME/.duckdb/cli/latest" >> $GITHUB_PATH
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - name: Install problematic deps
        run: zef install --/test File::Find
      - name: Install dependencies
        run: zef install --deps-only .
      - name: Run tests
        run: zef test -v .
